/**
 * 토픽 제목과 다르게 적힌 문항·답안을 잇는 다른 표기.
 *
 * 2026-10-04 검수 — 서브노트 599개 중 132개가 NS·기출 이력 0건, 81개가 답안 0건이었다.
 * 대부분은 문항이 없어서가 아니라 제목 열쇠가 문항 표기와 어긋나서였다.
 * 「결함허용 컴퓨터(FTS)」는 답안지가 10장 붙어 있는데 문항은 "결함 허용 시스템",
 * 「Banker's 알고리즘(은행가 알고리즘)」은 "은행가 알고리즘(Banker's Algorithm)" 으로 나와
 * 한 건도 못 찾았다.
 *
 * 사람이 읽는 표기 그대로 적는다(공백·기호는 매칭할 때 지운다). 영문은 낱말 경계를
 * 보므로(latinEdge) 짧은 약어도 다른 낱말 속에서 맞지 않는다.
 * 넣지 말 것: 다른 토픽에도 참인 넓은 말(「해싱」은 Consistent Hashing·비밀번호 해싱까지,
 * 「Bill of Materials」는 SBOM 까지, 「서비스화」는 아무 서비스 문항까지 끌어온다).
 */
export const TOPIC_ALIASES: Record<string, string[]> = {
  "결함허용 컴퓨터(FTS)": ["결함허용", "결함 허용", "Fault Tolerant", "Fault-Tolerant"],
  "CPU 처리과정": ["명령어 실행 사이클", "명령어 사이클", "Instruction Cycle", "메이저 상태", "Major State"],
  "기억장치 계층 구조 (Memory Hierarchy)": ["메모리 계층구조", "메모리 계층 구조", "기억장치 계층", "Memory Hierarchy"],
  "직접 사상과 연관 사상 페이징 기법": ["직접 사상", "연관 사상", "Direct Mapping", "Associative Mapping"],
  "Banker's 알고리즘(은행가 알고리즘)": ["은행가 알고리즘", "은행원 알고리즘", "Banker"],
  "프로세스(Process)와 스레드(Thread) 비교": ["프로세스와 쓰레드", "프로세스와 스레드"],
  "유닉스의 inode": ["inode", "i-node"],
  "라우팅 알고리즘(Routing Protocol, 거리벡터, 링크상태)": ["거리벡터 라우팅", "링크상태 라우팅", "Distance Vector Routing", "Link State Routing"],
  "그래프 순회(Graph Traversal)": ["그래프 탐색 알고리즘", "Depth First Search", "Breadth First Search"],
  "OSI 7 Layer (ISO 7498)": ["OSI 7 계층", "OSI 7계층"],
  "캐시(Cache) 메모리의 사상 방식(Mapping Scheme)": ["캐시 메모리 사상", "캐시메모리 사상", "캐시 사상", "캐시 메모리(Cache Memory) 주소 사상", "Cache Mapping"],
  "디스크 스케줄링(Disk Scheduling)": ["디스크 스케쥴링", "디스크스케줄링", "디스크스케쥴링"],
  "3점 산정": ["3점 추정", "3점 산정", "삼점 추정", "Three Point"],
  "품질통제도구, QC 7": ["QC 7", "QC7", "품질관리 7가지 도구", "품질 7가지 도구", "특성요인도"],
  "SW 품질비용": ["품질비용 항목", "품질 비용 항목", "Cost of Quality", "소프트웨어 품질비용", "SW 품질비용", "품질비용(COQ"],
  "터크만 팀 개발 5단계": ["터크만", "Tuckman"],
  "Agile 선언문과 12개 원칙": ["애자일 선언문", "Agile 선언문", "Agile Manifesto", "애자일 선언"],
  "데메테르의 법칙 (Law of Demeter)": ["데메테르", "디미터", "Law of Demeter"],
  "ISO/IEC/IEEE 42010:2022": ["42010"],
  "SW Architecture 구축 절차": ["아키텍처 구축 절차", "아키텍쳐 구축 절차"],
  "SW Architecture 평가": ["아키텍처 평가", "아키텍쳐 평가", "ATAM", "CBAM", "SAAM"],
  "릴리즈 엔지니어링": ["릴리즈 엔지니어링", "릴리스 엔지니어링", "Release Engineering"],
  "카오스 엔지니어링 (Chaos Engineering)": ["카오스 테스트", "Chaos Test", "카오스 엔지니어링", "Chaos Engineering"],
  "정서 인공지능(Affective AI)": ["Affective AI", "Affective Computing", "감성 컴퓨팅", "정서 인공지능", "감성 인공지능"],
  "거리 공식(Distance Formula)": ["유클리디안 거리", "유클리드 거리", "맨하탄 거리", "맨해튼 거리", "마할라노비스", "민코프스키"],
  "앙상블 학습(Ensemble Learning)": ["앙상블", "Ensemble", "Bagging", "배깅", "부스팅", "Boosting", "랜덤 포레스트", "Random Forest"],
  "SVD(Singular Value Decomposition)": ["특이값 분해", "특잇값 분해", "Singular Value Decomposition", "SVD"],
  "검색 삽입 생성(RIG, Retrieval Interleaved Generation)": ["Retrieval Interleaved", "검색 삽입 생성"],
  LangGraph: ["LangGraph", "랭그래프"],
  "LAM(Large Action Model)": ["Large Action Model", "대규모 행동 모델", "대형 행동 모델", "대형 액션 모델"],
  "대형개념모델(LCM, Large Concept Models)": ["Large Concept Model", "대형개념모델", "대형 개념 모델"],
  "테스트 타임 컴퓨팅(Test-Time Compute)": ["Test-Time Compute", "테스트 타임 컴퓨팅"],
  "테스트 타임 스케일링(Test-Time Scaling, TTS)": ["Test-Time Scaling", "테스트 타임 스케일링"],
  MLPerf: ["MLPerf"],
  "Diffusion 모델": ["Diffusion Model", "확산 모델", "Stable Diffusion", "스테이블 디퓨전", "디퓨전 모델"],
  "멀티모달 데이터의 품질검증 방법": ["멀티모달 데이터의 품질검증", "멀티모달 데이터 품질"],
  "모델 드리프트(Model Drift) — 컨셉 드리프트 & 데이터 드리프트": ["컨셉 드리프트", "Concept Drift", "데이터 드리프트", "Data Drift", "모델 드리프트", "Model Drift"],
  "ISO/IEC 23894": ["23894"],
  "AI RMF(AI Risk Management Framework)": ["AI RMF", "NIST AI"],
  "ISO/IEC 42119-2": ["42119"],
  "MCP 보안취약점 및 대응방안": ["MCP 보안", "MCP 취약점"],
  "AI BOM(Artificial Intelligence Bill of Materials)": ["AI BOM", "AI-BOM", "AIBOM"],
  "공공 AX 전략": ["공공 AX", "공공부문 AX"],
  "인공지능 경영시스템(ISO 42001:2023)": ["42001"],
  "AI Ready Data": ["AI Ready", "AI-Ready"],
  "인공지능 투명성 확보 가이드라인": ["투명성 확보 가이드"],
  "고영향 인공지능(AI) 판단 가이드라인": ["고영향"],
  "인공지능 영향평가 가이드라인": ["인공지능 영향평가", "AI 영향평가"],
  "인공지능 생성물 워터마크 적용 기술": ["워터마크"],
  "COT(Chain of Thought)": ["Chain of Thought", "Chain-of-Thought", "사고의 사슬", "생각의 사슬"],
  "왜도(Skewness) & 첨도(Kurtosis)": ["왜도", "첨도", "Skewness", "Kurtosis"],
  "연관성 분석(association analysis) - 기초통계": ["상관분석", "상관 분석", "상관계수", "상관 계수", "공분산", "교차분석"],
  "AIC(Akaike information Criterion) & BIC(Bayesian information Criterion)": ["Akaike", "AIC", "BIC"],
  "리그레이션(회귀, Regression) 테스트": ["회귀 테스트", "회귀테스트", "Regression Test", "리그레션 테스트", "리그레이션 테스트", "회귀 시험"],
  "Back to Back 테스트": ["Back to Back", "Back-to-Back", "백투백"],
  "Test Process": ["테스트 프로세스", "Test Process"],
  "Lehman의 Software 변화의 원리": ["Lehman", "레만", "리먼의"],
  "ISO/IEC/IEEE 14764": ["14764", "소프트웨어 유지보수 프로세스"],
  "CMMI 3.0": ["CMMI"],
  "ISO/IEC 25010:2023": ["25010"],
  "상용소프트웨어 품질성능 평가 시험": ["품질성능 평가", "품질성능평가"],
  "SW 규모산정": ["SW 규모 산정", "SW 규모산정", "소프트웨어 규모 산정", "소프트웨어 규모산정", "소프트웨어 개발에 필요한 규모", "사업 규모 산정", "기능점수", "Function Point", "COCOMO"],
  "지능정보기술 감리 실무 가이드 - 클라우드 감리": ["클라우드 감리"],
  "지능정보기술 감리 실무 가이드 - 빅데이터 감리": ["빅데이터 감리"],
  "정보시스템 감리결과보고서 (구성, 보고사항)": ["감리결과보고서", "감리 결과 보고서", "감리보고서"],
  "B-Tree(Balanced Tree)": ["B-Tree", "B Tree", "B트리", "B+Tree", "B+ Tree", "B*Tree"],
  "알고리즘 성능평가": ["시간복잡도", "시간 복잡도", "공간복잡도", "점근 표기", "빅오", "Big-O"],
  "해싱과 충돌해결방법": ["해싱 기법", "해시 충돌", "해시충돌", "선형 탐사", "Linear Probing", "체이닝"],
  "전송부호화(소스 코딩, 채널 코딩, 라인 코딩)": ["라인 코딩", "채널 코딩", "소스 코딩", "Line Coding", "Channel Coding"],
  "QAM(Quadrature Amplitude Modulation)": ["QAM", "직교 진폭"],
  "IPv4와 IPv6 터널링": ["IPv6 전환", "듀얼스택", "듀얼 스택", "Dual Stack", "6to4", "ISATAP", "Teredo"],
  "RARP(Reverse Address Resolution Protocol)": ["RARP", "Reverse Address"],
  "C-RAN(Centralized / Cloud RAN)": ["C-RAN", "Cloud RAN", "Centralized RAN"],
  "O-RAN": ["O-RAN", "Open RAN", "오픈랜"],
  "비지상네트워크(NTN, Non-Terrestrial Networks)": ["NTN", "Non-Terrestrial", "비지상", "저궤도 위성"],
  "SD-WAN(Software Defined-Wide Area Network)": ["SD-WAN", "SDWAN"],
  "Sliding Window & 네이글(Nagle's) 알고리즘": ["Sliding Window", "슬라이딩 윈도우", "Nagle", "네이글"],
  "ANSI/SPARC 모델(3-단계 데이터베이스 구조) / 데이터 독립성": ["ANSI/SPARC", "ANSI-SPARC", "3단계 스키마", "3층 스키마", "데이터 독립성"],
  "데이터베이스 반정규화(De-Normalization)": ["반정규화", "역정규화", "De-Normalization", "Denormalization"],
  "DB 회복기법": ["회복 기법", "회복기법", "장애 회복", "즉시 갱신", "지연 갱신", "Shadow Paging", "그림자 페이징"],
  "MVCC(다중 버전 동시성 제어) 2가지 유형": ["MVCC", "다중 버전"],
  "분산 DB": ["분산 데이터베이스", "분산 DB", "분산 트랜잭션", "2PC", "2 Phase Commit"],
  "CAP 이론과 BASE 이론": ["CAP 이론", "CAP Theorem", "BASE 이론", "PACELC"],
  "ANN(Approximate Nearest Neighbor) 알고리즘": ["Approximate Nearest", "근사 최근접", "HNSW"],
  "공공데이터 예방적 품질관리 진단 가이드": ["예방적 품질"],
  "데이터 품질인증 가이드라인 - DQ인증 (2025.02.26)": ["DQ인증", "DQ 인증", "데이터 품질인증", "DQC"],
  "연관성 분석(association analysis) - 데이터마이닝": ["연관규칙", "연관 규칙", "Association Rule", "장바구니 분석", "Apriori"],
  "DHP(Direct Hashing & Pruning) 알고리즘": ["Direct Hashing", "DHP"],
  "FP(Frequent Pattern)-Growth 알고리즘": ["FP-Growth", "FP Growth", "Frequent Pattern", "FP-Tree"],
  "DaaP(Data as a product)": ["DaaP", "Data as a Product", "데이터 프로덕트", "Data Product"],
  "ISO 38500:2024": ["38500"],
  "Ansoff Matrix": ["Ansoff", "앤소프"],
  "MECE와 LISS": ["MECE", "LISS"],
  "ISP 및 ISMP 수립 공통가이드 9판(2025.05)": ["ISMP", "ISP 수립", "정보화전략계획"],
  "기술수용 주기(Technology Adoption Life Cycle)": ["기술수용주기", "기술수용 주기", "기술 수용 주기", "캐즘", "Chasm", "Technology Adoption"],
  "서비타이제이션(Servitization)": ["서비타이제이션", "Servitization", "제조의 서비스화"],
  "의도 경제(Intention Economy)": ["의도 경제", "Intention Economy"],
  "암호학적 보안 강도(Security Strength)": ["보안 강도", "Security Strength"],
  "암호 분석 공격(Cryptanalysis Attacks) 기법": ["암호 분석", "암호분석", "Cryptanalysis", "선택 평문", "기지 평문"],
  "DRDoS(Distributed Reflection DoS)": ["DRDoS", "반사 공격", "증폭 공격", "Reflection DDoS", "Amplification Attack"],
  "루트킷(Rootkit)": ["루트킷", "Rootkit"],
  "DNS 싱크홀(Sinkhole)": ["싱크홀", "Sinkhole"],
  "DRM(Digital Right Management)": ["Digital Right"],
  "디지털 워터마킹(Digital Watermarking)": ["워터마킹", "Watermarking"],
  "차세대 SIEM(Security Information and Event Management)": ["SIEM", "ESM"],
  "EDR(Endpoint Detection and Response)": ["EDR", "Endpoint Detection"],
  "DMARC(Domain-based Message Authentication, Reporting and Conformance)": ["DMARC", "DKIM"],
  "ISO 27017": ["27017"],
  "개인정보 프라이버시 8원칙": ["OECD 프라이버시", "OECD 8원칙", "프라이버시 8원칙", "OECD 개인정보"],
  "ISO 27018": ["27018"],
  "ISO 27701": ["27701"],
  "ISO/IEC 20889": ["20889"],
  "정보보호제품 평가·인증(CC 평가·인증) 제도": ["CC 인증", "CC인증", "공통평가기준", "Common Criteria", "CC 평가"],
  "자율주행 자동차 보안취약점 및 대응방안": ["자율주행 자동차 보안", "자율주행차 보안", "자동차 보안", "차량 보안"],
  "사이버 보안 성숙도 모델 인증(CMMC, Cybersecurity Maturity Model Certification)": ["CMMC"],
  "사이버 게놈(Cyber genome)": ["사이버 게놈", "Cyber Genome"],
  "스마트시티 보안취약점 및 대응방안": ["스마트시티 보안", "스마트 시티 보안"],
  "스마트팩토리 보안취약점 및 대응방안": ["스마트팩토리 보안", "스마트 팩토리 보안", "스마트공장 보안", "제어시스템 보안"],
  "클라우드 컴퓨팅 취약점, 대응기술": ["클라우드 취약점", "클라우드 컴퓨팅 취약점", "클라우드 컴퓨팅 보안", "클라우드 보안 위협", "클라우드 보안위협"],
  "ISO/IEC 25059:2023(AI 품질모델)": ["25059"],
  "AP2(Agent Payment Protocol)": ["AP2", "Agent Payment", "Agent Payments"],
  "UCP(Universal Commerce Protocol)": ["Universal Commerce"],
  "ACP(Agentic Commerce Protocol)": ["Agentic Commerce"],
  "데이터 스페이스(Data Space)": ["데이터 스페이스", "데이터스페이스", "Data Space", "Dataspace"],
  "데이터 상호 운용성 & 데이터 이동권": ["데이터 이동권", "전송요구권", "데이터 상호운용성", "데이터 상호 운용성"],
  "AI OS(Artificial Intelligence Operating System)": ["AI OS", "AIOS", "AI 운영체제"],
  "OWASP Agentic AI 위협 및 대응방안(Agentic AI Threats and Mitigations)": ["Agentic AI Threats", "에이전틱 AI 위협", "에이전틱 AI 보안"],
  "활동기간 산정기법": ["활동기간 산정", "활동 기간 산정", "기간 산정 기법"],
  "AI-DLC(AI-Driven SDLC)": ["AI-DLC", "AI Driven Development", "AI-Driven Development"],
  "페르소나 (Persona)": ["페르소나", "Persona"],
  "싱글턴 패턴 (Singleton pattern)": ["싱글턴", "싱글톤", "Singleton"],
  "UML의 4+1 View Model": ["4+1"],
  "SDD(Spec-Driven Development)": ["Spec-Driven", "Spec Driven", "스펙 주도", "명세 주도"],
  "정규화, 규제화, 표준화": ["규제화", "Regularization"],
  "컨텍스트 엔지니어링(Context Engineering)": ["컨텍스트 엔지니어링", "Context Engineering"],
  "프롬프트 튜닝(Prompt Tuning)": ["Prompt Tuning", "프롬프트 튜닝", "Soft Prompt"],
  "랭체인(LangChain)": ["LangChain", "랭체인"],
  "AI 레드팀(Red team) 테스트": ["레드팀", "Red Team", "레드 팀"],
  "AI 네이티브 개발 플랫폼(AI-Native Development Platform)": ["AI 네이티브 개발", "AI-Native Development", "AI Native Development"],
  "A2A(Agent2Agent) 프로토콜": ["Agent2Agent", "Agent-to-Agent", "Agent to Agent", "A2A Protocol", "A2A 프로토콜"],
  "생성형AI 데이터 품질관리 가이드 v2.0": ["생성형 AI 데이터 품질", "생성형AI 데이터 품질", "생성형 인공지능 데이터 품질"],
  "확률분포와 확률 밀도 함수": ["확률분포", "확률 분포", "확률밀도", "확률 밀도"],
  "Test Exit Criteria": ["Exit Criteria", "종료 기준", "테스트 완료 기준"],
  "Passive WiFi": ["Passive Wi-Fi", "Passive WiFi", "백스캐터", "Backscatter"],
  "Apriori 알고리즘": ["Apriori", "아프리오리"],
  "DRaaS(Disaster Recovery as a Service)": ["DRaaS", "Disaster Recovery as a Service"],
  "PDCA(Plan-Do-Check-Act, Deming Cycle)": ["PDCA", "Deming", "데밍"],
  "Shannon의 암호 설계 원칙": ["혼돈과 확산", "혼돈(Confusion)과 확산", "Confusion과 Diffusion", "Shannon의 암호", "섀넌의 암호"],
  "딥보이스(Deep Voice) 피싱": ["딥보이스", "Deep Voice", "보이스 피싱", "보이스피싱"],
  "OWASP Top 10:2025": ["OWASP Top 10", "OWASP Top10"],
  "Secure Software Development Framework(SSDF)": ["SSDF"],
  "핑거프린팅(Fingerprinting)": ["핑거프린팅", "Fingerprinting"],
  "위협 모델링(Threat Modeling)": ["위협 모델링", "위협모델링", "Threat Model", "STRIDE"],
  "기밀컴퓨팅(Confidential Computing)": ["기밀 컴퓨팅", "기밀컴퓨팅", "Confidential Computing", "Trusted Execution"],
  "AI Agent 보안위협": ["에이전트 보안", "Agent 보안", "AI Agent 보안", "에이전트의 보안"],
};
